import type { Car } from "./types";

/**
 * Shown only until real cars are added in Supabase (matches supabase/seed.sql,
 * so once that seed runs the live data looks the same).
 */
export const FALLBACK_CARS: Car[] = [
  {
    id: "etios", name: "Toyota Etios", slug: "etios", category: "Sedan", seating_capacity: 4,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Comfortable, economical sedan for city runs, airport drops and budget outstation trips.",
    features: ["Boot space for 2 large bags", "Ideal for 1 to 4 travellers"],
    image_url: "/ETIOS.webp", featured: true, active: true, display_order: 1,
    car_pricing: { car_id: "etios", day_12hr: 1500, day_24hr: 2500, day_fuel_km_per_litre: 10, day_chauffeur_12hr: 400, day_chauffeur_24hr: 700, day_extra_hour: 200, reg_4hr_40km: 1400, reg_8hr_80km: 2200, reg_extra_hour: 200, reg_extra_km: 13, out_per_km: 13, out_chauffeur: 500, out_min_km: 350, out_notes: "Above 350 km, outstation tariff applies." },
  },
  {
    id: "swift-dzire", name: "Swift Dzire", slug: "swift-dzire", category: "Sedan", seating_capacity: 4,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Compact sedan that is easy through city traffic and comfortable on the highway.",
    features: ["Boot space for 2 large bags", "Ideal for 1 to 4 travellers"],
    image_url: "/SWIFT.webp", featured: true, active: true, display_order: 2,
    car_pricing: { car_id: "swift-dzire", day_12hr: 1500, day_24hr: 2500, day_fuel_km_per_litre: 10, day_chauffeur_12hr: 400, day_chauffeur_24hr: 700, day_extra_hour: 200, reg_4hr_40km: 1400, reg_8hr_80km: 2200, reg_extra_hour: 200, reg_extra_km: 13, out_per_km: 13, out_chauffeur: 500, out_min_km: 350, out_notes: "Above 350 km, outstation tariff applies." },
  },
  {
    id: "nissan-sunny", name: "Nissan Sunny", slug: "nissan-sunny", category: "Sedan", seating_capacity: 4,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Roomy sedan with generous rear legroom for longer local days.",
    features: ["Generous rear legroom", "Ideal for 1 to 4 travellers"],
    image_url: "/sunny.webp", featured: false, active: true, display_order: 3,
    car_pricing: { car_id: "nissan-sunny", day_12hr: 2000, day_24hr: 2500, day_fuel_km_per_litre: 8, day_chauffeur_12hr: 500, day_chauffeur_24hr: 600, day_extra_hour: 200, reg_4hr_40km: 2000, reg_8hr_80km: 3000, reg_extra_hour: 100, reg_extra_km: 12, out_per_km: 12, out_chauffeur: 500, out_min_km: null, out_notes: null },
  },
  {
    id: "honda-city", name: "Honda City", slug: "honda-city", category: "Premium Sedan", seating_capacity: 4,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Refined premium sedan for business meetings and family occasions.",
    features: ["Premium interior", "Ideal for executives"],
    image_url: "/city.webp", featured: false, active: true, display_order: 4,
    car_pricing: { car_id: "honda-city", day_12hr: 5000, day_24hr: 7500, day_fuel_km_per_litre: 6, day_chauffeur_12hr: 500, day_chauffeur_24hr: 1000, day_extra_hour: 200, reg_4hr_40km: 2500, reg_8hr_80km: 5000, reg_extra_hour: 200, reg_extra_km: 50, out_per_km: 50, out_chauffeur: 500, out_min_km: null, out_notes: null },
  },
  {
    id: "innova", name: "Toyota Innova", slug: "innova", category: "MUV", seating_capacity: 7,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Spacious seven-seater for families and groups, local or outstation.",
    features: ["Seats up to 7", "Room for group luggage"],
    image_url: "/INNOVA.webp", featured: true, active: true, display_order: 5,
    car_pricing: { car_id: "innova", day_12hr: 2000, day_24hr: 3000, day_fuel_km_per_litre: 8, day_chauffeur_12hr: 500, day_chauffeur_24hr: 700, day_extra_hour: 300, reg_4hr_40km: 2500, reg_8hr_80km: 3000, reg_extra_hour: 300, reg_extra_km: 17, out_per_km: 17, out_chauffeur: 700, out_min_km: 450, out_notes: "Above 450 km, outstation tariff applies." },
  },
  {
    id: "innova-crysta", name: "Toyota Innova Crysta", slug: "innova-crysta", category: "Premium MUV", seating_capacity: 7,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "The most requested car for long highway trips: quiet, spacious and comfortable.",
    features: ["Seats up to 7", "Captain seats on select cars", "Long-trip comfort"],
    image_url: "/crysta.webp", featured: true, active: true, display_order: 6,
    car_pricing: { car_id: "innova-crysta", day_12hr: 2500, day_24hr: 3500, day_fuel_km_per_litre: 8, day_chauffeur_12hr: 500, day_chauffeur_24hr: 700, day_extra_hour: 350, reg_4hr_40km: 3000, reg_8hr_80km: 4000, reg_extra_hour: 350, reg_extra_km: 19, out_per_km: 19, out_chauffeur: 700, out_min_km: 450, out_notes: "Above 450 km, outstation tariff applies." },
  },
  {
    id: "camry", name: "Toyota Camry", slug: "camry", category: "Luxury Sedan", seating_capacity: 4,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Executive sedan for corporate guests, VIP pickups and weddings.",
    features: ["Executive rear seat", "Corporate and VIP travel"],
    image_url: "/CAM.webp", featured: false, active: true, display_order: 7,
    car_pricing: { car_id: "camry", day_12hr: 10000, day_24hr: 15000, day_fuel_km_per_litre: 6, day_chauffeur_12hr: 750, day_chauffeur_24hr: 1000, day_extra_hour: 300, reg_4hr_40km: 5000, reg_8hr_80km: 10000, reg_extra_hour: 400, reg_extra_km: 70, out_per_km: 70, out_chauffeur: 1000, out_min_km: null, out_notes: null },
  },
  {
    id: "fortuner", name: "Toyota Fortuner", slug: "fortuner", category: "Premium SUV", seating_capacity: 6,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Commanding SUV with presence, comfort and space.",
    features: ["Seats up to 6", "Premium SUV"],
    image_url: "/fortuner-2.webp", featured: true, active: true, display_order: 8,
    car_pricing: { car_id: "fortuner", day_12hr: 10000, day_24hr: 15000, day_fuel_km_per_litre: 6, day_chauffeur_12hr: 750, day_chauffeur_24hr: 1000, day_extra_hour: 300, reg_4hr_40km: 5000, reg_8hr_80km: 10000, reg_extra_hour: 1000, reg_extra_km: 50, out_per_km: 50, out_chauffeur: 1500, out_min_km: null, out_notes: null },
  },
  {
    id: "new-fortuner", name: "New Toyota Fortuner", slug: "new-fortuner", category: "Premium SUV", seating_capacity: 6,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Latest-generation Fortuner for events, weddings and premium travel.",
    features: ["Latest model", "Seats up to 6"],
    image_url: "/newf.webp", featured: false, active: true, display_order: 9,
    car_pricing: { car_id: "new-fortuner", day_12hr: 15000, day_24hr: 20000, day_fuel_km_per_litre: 6, day_chauffeur_12hr: 750, day_chauffeur_24hr: 1000, day_extra_hour: 1000, reg_4hr_40km: 8000, reg_8hr_80km: 15000, reg_extra_hour: 1000, reg_extra_km: 60, out_per_km: 60, out_chauffeur: 1000, out_min_km: null, out_notes: null },
  },
  {
    id: "benz-c220", name: "Mercedes-Benz C 220", slug: "benz-c220", category: "Luxury Sedan", seating_capacity: 4,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Mercedes-Benz luxury for weddings, VIP guests and special occasions.",
    features: ["Luxury interior", "Wedding and VIP travel"],
    image_url: "/benz-c-2201.webp", featured: false, active: true, display_order: 10,
    car_pricing: { car_id: "benz-c220", day_12hr: 20000, day_24hr: 30000, day_fuel_km_per_litre: 6, day_chauffeur_12hr: 750, day_chauffeur_24hr: 1500, day_extra_hour: 1000, reg_4hr_40km: 10000, reg_8hr_80km: 20000, reg_extra_hour: 1000, reg_extra_km: 70, out_per_km: 70, out_chauffeur: 1500, out_min_km: null, out_notes: null },
  },
  {
    id: "bmw-7-series", name: "BMW 7 Series", slug: "bmw-7-series", category: "Luxury Sedan", seating_capacity: 4,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Flagship luxury sedan for dignitaries and premium events.",
    features: ["Flagship luxury", "Chauffeur-driven"],
    image_url: "/bmw.webp", featured: false, active: true, display_order: 11,
    car_pricing: { car_id: "bmw-7-series", day_12hr: 20000, day_24hr: 30000, day_fuel_km_per_litre: 6, day_chauffeur_12hr: 1000, day_chauffeur_24hr: 1500, day_extra_hour: 1000, reg_4hr_40km: 10000, reg_8hr_80km: 20000, reg_extra_hour: 1000, reg_extra_km: 100, out_per_km: 110, out_chauffeur: 1500, out_min_km: null, out_notes: null },
  },
  {
    id: "audi-q7", name: "Audi Q7", slug: "audi-q7", category: "Luxury SUV", seating_capacity: 6,
    fuel_type: null, transmission: null, air_conditioned: true,
    description: "Luxury SUV for high-profile guests and grand occasions.",
    features: ["Luxury SUV", "Seats up to 6"],
    image_url: "/93c7oua-1555653.webp", featured: false, active: true, display_order: 12,
    car_pricing: { car_id: "audi-q7", day_12hr: 25000, day_24hr: 35000, day_fuel_km_per_litre: 6, day_chauffeur_12hr: 1000, day_chauffeur_24hr: 1500, day_extra_hour: 1000, reg_4hr_40km: 15000, reg_8hr_80km: 25000, reg_extra_hour: 1000, reg_extra_km: 120, out_per_km: 120, out_chauffeur: 1500, out_min_km: null, out_notes: null },
  },
];
